// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'id'

export type Locales =
	| 'de'
	| 'en'
	| 'id'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​a​i​ ​{​n​a​m​e​}​!​ ​S​i​l​a​k​a​n​ ​b​e​r​i​ ​b​i​n​t​a​n​g​ ​j​i​k​a​ ​A​n​d​a​ ​m​e​n​y​u​k​a​i​ ​p​r​o​y​e​k​ ​i​n​i​:​ 
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * S​e​m​o​g​a​ ​{​n​a​m​e​}​ ​b​e​r​i​s​t​i​r​a​h​a​t​ ​d​e​n​g​a​n​ ​t​e​n​a​n​g​.
	 * @param {string} name
	 */
	RIP: RequiredParams<'name'>
}

export type TranslationFunctions = {
	/**
	 * Hai {name}! Silakan beri bintang jika Anda menyukai proyek ini: 
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Semoga {name} beristirahat dengan tenang.
	 */
	RIP: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
